@startuml

!include <C4/C4_Component>

Container_Boundary(presentation, "Präsentation", $tags="Label1+Label2") {
  AddProperty("var", 2)
  Component(web, "web", $tags="Label3+Label4")
}

AddProperty("Test", "1")
Component(component1, "ComponentName", "ComponentTechnology", "ComponentDescription", "ignoreSprite", "ComponentTag") {
    Component(a, "b", "c", "d")
}

Person(test111, "Test")
AddProperty("Blub", "bla")
Boundary(abc, "a", "Example", $tags="Layer") {
    System(abcSystem, "AbcSystemName")
}

Enterprise_Boundary(def, "d", "System") {
    System(defSystem, "DefSystemName")
}

Rel(abc, def, "")

Component(minComponent, "MinComponent")
ComponentDb(componentDb1, "ComponentDbName", "ComponentDbTechnology", "ComponentDbDescription", $tags="ComponentDbTag")
ComponentQueue(componentQueue1, "ComponentQueueName", "ComponentQueueTechnology", "ComponentQueueDescription", $tags="ComponentQueueTag")
BiRel(componentDb1, componentQueue1, "")

Component_Ext(component_ext1, "ComponentExtName", "ComponentExtTechnology", "ComponentExtDescription", $tags="ComponentExtTag")
ComponentDb_Ext(componentDb_ext1, "ComponentDbExtName", "ComponentDbExtTechnology", "ComponentDbExtDescription", $tags="ComponentDbTag")
ComponentQueue_Ext(componentQueue_ext1, "ComponentQueueExtName", "ComponentQueueExtTechnology", "ComponentQueueExtDescription", $tags="ComponentQueueTag")

Container(minContainer, "MinContainer")
Container(container1, "ContainerName", "ContainerTechnology", "ContainerDescription", "ignoreSprite", "ContainerTag")
ContainerDb(containerDb1, "ContainerDbName", "ContainerDbTechnology", "ContainerDbDescription", $tags="ContainerDbTag")
ContainerQueue(containerQueue1, "ContainerQueueName", "ContainerQueueTechnology", "ContainerQueueDescription", $tags="ContainerQueueTag")

Container_Ext(container_ext1, "ContainerExtName", "ContainerExtTechnology", "ContainerExtDescription", $tags="ContainerExtTag")
ContainerDb_Ext(containerDb_ext1, "ContainerDbExtName", "ContainerDbExtTechnology", "ContainerDbExtDescription", $tags="ContainerDbTag")
ContainerQueue_Ext(containerQueue_ext1, "ContainerQueueExtName", "ContainerQueueExtTechnology", "ContainerQueueExtDescription", $tags="ContainerQueueTag")

System(minSystem, "MinSystem")
System(system1, "SystemName", "SystemDescription", "ignoreSprite", "SystemTag")
SystemDb(systemDb1, "SystemDbName", "SystemDbDescription", $tags="SystemDbTag")
SystemQueue(systemQueue1, "SystemQueueName", "SystemQueueDescription", $tags="SystemQueueTag")

System_Ext(system_ext1, "SystemExtName", "SystemExtDescription", $tags="SystemExtTag")
SystemDb_Ext(systemDb_ext1, "SystemDbExtName", "SystemDbExtDescription", $tags="SystemDbTag")
SystemQueue_Ext(systemQueue_ext1, "SystemQueueExtName", "SystemQueueExtDescription", $tags="SystemQueueTag")

Component($label=alias, $alias=label, "Tech", $descr = "asjsa", $tags="abab", $sprite="ababa")

AddProperty("A", "B")
Rel(component1, componentDb1, "Uses", "Uses_Technology", $tags="USES_DB")

SHOW_LEGEND()

@enduml